blank_issues_enabled: false
contact_links:
  - name: Feature or Project Idea Request
    url: https://github.com/pieces-app/opensource/discussions/new/choose
    about: Post your project idea in discussions for the Pieces team and community to discuss!